### PR TITLE
Feature/levels

### PR DESCRIPTION
**Pull request by nyanofthemoon**
Added levels

### CODE REVIEW

**Comment by nyanofthemoon** [comment]
@tlhunter :)

**Comment by tlhunter** [comment]
Ooh, interesting! I'll try to review this tonight.

**Comment by tlhunter** [comment]
Can you separate the asset changes into their own PR as they change gameplay and aren't related to the primary purpose of this PR.

**Comment by tlhunter** [comment]
Also, this has all the changes of your other PR, you should separate those as well. For example, the keyup/keydown issue will prevent this PR from going through.

**Comment by nyanofthemoon** [comment]
@tlhunter Sure. :)

**Pull request closed without merging**
